---

# Set local timezone
- name: Set local timezone
  command: arch-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

- name: Generate adjtime file
  command: arch-chroot /mnt hwclock --systohc

# Setup locales
- name: Configure locale.gen
  lineinfile:
    dest: /mnt/etc/locale.gen
    regexp: '{{ item.regex }}'
    line: '{{ item.line }}'
  loop:
    - {regex: en_US\.UTF-8 UTF-8, line: en_US.UTF-8 UTF-8}
    - {regex: en_US ISO-8859-1, line: en_US ISO-8859-1}

- name: Create locale.conf
  copy:
    content: "LANG=en_US.UTF-8"
    dest: /mnt/etc/locale.conf

- name: Generate locales
  command: arch-chroot /mnt locale-gen

# Set keyboard layout to german
- name: Create locale.conf
  copy:
    content: "KEYMAP=de"
    dest: /mnt/etc/vconsole.conf