---

# Repartition install drive
- name: Wipe install drive and all its partitions
  command: find /dev -wholename "{{ install_drive }}*" -exec wipefs --force --all {} \;

- name: Create boot partition
  parted:
    device: '{{ install_drive }}'
    label: gpt
    number: 1
    part_end: 512MB
    name: boot
    flags: [boot, esp]
    state: present

- name: Create root partition
  parted:
    device: '{{ install_drive }}'
    label: gpt
    number: 2
    part_start: 512MB
    name: root
    flags: [lvm]
    state: present

# Create filesystems
- name: Create FAT32 filesystem in boot partition
  filesystem:
    dev: '{{ install_drive }}{{ boot_partition_suffix }}'
    fstype: vfat
    opts: -F32
    force: yes

- name: Create ext4 filesystem in root volume
  filesystem:
    dev: '{{ install_drive }}{{ root_partition_suffix }}'
    fstype: ext4
    force: yes

# Mount filesystems
- name: Mount root filesystem
  mount:
    path: /mnt
    src: '{{ install_drive }}{{ root_partition_suffix }}'
    fstype: ext4
    state: mounted

- name: Create mountpoint for boot volume
  file:
    path: /mnt/boot
    state: directory

- name: Mount boot filesystem
  mount:
    path: /mnt/boot
    src: '{{ install_drive }}{{ boot_partition_suffix }}'
    fstype: vfat
    state: mounted